### ISSUE TITLE
a support for raw hash holosource refs

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/hologit#185]
Currently, if you try to reference a commit hash in a holosource, e.g.:

```toml
[holosource]
url = "https://github.com/michelf/php-markdown.git"
ref = "27bfa1902296eaaaaeef7838af4964589805f90a"
```

You'll get an error:

```console
error: ref 27bfa1902296eaaaaeef7838af4964589805f90a must start with refs/
```

Raw commit hashes should be usable here
